### ISSUE TITLE
Running error with copymakeborder_plugin

### ISSUE THREAD

**Issue by jingweimo** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#2]
I am following the instructions in the book page 226-233 to run the first example on `copymakeboder_plugin`. After building `Computer_Vision` project, there is no `cvplugins` folder generated in the build folder. My build results in three subfolders: `copymakeborder_plugin`, `mainapp `and `temp_plugin`.

I tried to copy the `CopyMakeBorder_Plugin.lib `(I assumed it was the library file needed) in the `copymakeborder_plugin` build folder, to the `mainapp` build folder, and then run the `mainapp `, but got the error message windows: 

No Plugins   `This application cannot work without plugins! Make sure that/cvplugins/folder exists in the same folder as the application and that there are some filter plugins inside it.`

Is this folder automatically generated after building?

I am using Qt5.8 with OpenCV3.4 in windows10.  

Thanks in advance!

**Comment by amahta** [comment]
@jingweimo, your application build folder is where the *.exe for the main app resides. You need to manually create a folder called cvplugins in that folder and copy the plugin *.dll file into it. Not *.lib, but *.dll

Is this clear enough? If not please let me know the exact path to where your build folder is so that I can help you out more clearly.

**Comment by jingweimo** [comment]
Thanks!!
