### ISSUE TITLE
Run ch7 keypoint_plugin for keypoint detection

### ISSUE THREAD

**Issue by jingweimo** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#3]
Hello, I am reading chapter 7 of your new book on opencv3-qt5. For experimenting with the presented keypoint detection algorithms, I put the `keypoint_plug` in the context `computer_vision `project developed the previous chapters. 

I have got a plugin error message:  `"Select a secondary image first!" ` (for the generated `Computer Vision `GUI, I loaded the image as shown in the book). Switching any algorithm available gives the message. I feel only image should be fine with keypoint detection rather than matching.

If I perform the matching operation, the interface is easily to be crashed for some reason. 

Working environment: OpenCV3.4 + Qt5.8

Thanks

**Comment by amahta** [comment]
Secondary image is the one you need to choose using the plugin user interface. Hope this helps.

**Comment by jingweimo** [comment]
Thanks you very much! It is clear !

**Comment by amahta** [comment]
@jingweimo you can close the issue if it is solved now :)

**Comment by jingweimo** [comment]
I have one follow-up question on implementing the example given in page293-301, on the extracting and matching descriptors. I have tested those codes, without being integrated into the computer vision project. There is an error in the step of matching descriptors: 
`opencv error: unsupported format or combination of formats (type=0 in cv::flann::buildindex_,`

**Comment by amahta** [comment]
Sorry to get back to you late @jingweimo , Easter holidays :)

By default AKAZE::create() function uses AKAZE::DESCRIPTOR_MLDB which is not a floating-point descriptor type. Therefore DescriptorMather fails when match() is called, since FLANNBASED descriptor type requires floating point descriptors. This is already mentioned in the explanations but unfortunately the example code misses a crucial parameter, and all the blame is on me :( Please replace the following line in your code:

`Ptr<AKAZE> akaze = AKAZE::create();`

with this:

`Ptr<AKAZE> akaze = AKAZE::create(AKAZE::DESCRIPTOR_KAZE);`

This will make sure KAZE parameter types are used and that your descriptor type is of floating point type. Try again and let me know if this helps.

Let me know if you have any other questions.

**Comment by amahta** [comment]
Just an additional note, if you want to use MLDB (i.e. without passing any params to AKAZE::create) then you can use Brute Force for matching instead of flann based, like this:

`descMather = DescriptorMatcher::create(DescriptorMatcher::BRUTEFORCE);`

**Comment by jingweimo** [comment]
Thanks for your kind explanations!
